"""
Initialize or create the trained models directory structure
This module ensures ML models are properly loaded or initialized
"""

import os
import joblib
import numpy as np
from pathlib import Path

def setup_models_directory():
    """Create models directory structure"""
    models_dir = Path('./models')
    models_dir.mkdir(exist_ok=True)
    print(f"✓ Models directory ready at: {models_dir}")


def check_models_exist():
    """Check if trained models exist"""
    models_dir = Path('./models')
    required_files = [
        'xgboost_model.pkl',
        'lightgbm_model.pkl', 
        'random_forest_model.pkl',
        'gradient_boosting_model.pkl',
        'logistic_regression_model.pkl',
        'svm_model.pkl',
        'scaler.pkl',
        'pca.pkl'
    ]
    
    missing = []
    for file in required_files:
        if not (models_dir / file).exists():
            missing.append(file)
    
    if missing:
        print("⚠ Missing model files:")
        for file in missing:
            print(f"  - {file}")
        print("\nRun: python train_model.py to train models")
        return False
    
    print("✓ All model files found")
    return True


def create_dummy_models():
    """Create dummy models for testing (when training not done)"""
    models_dir = Path('./models')
    models_dir.mkdir(exist_ok=True)
    
    # Create dummy numpy arrays for demonstration
    dummy_data = np.array([[0.5, 0.5, 0.5] * 5])  # 15 features
    
    print("Creating placeholder models for testing...")
    # Models will be generated by train_model.py
    print("✓ Setup ready - Run train_model.py to generate actual models")


if __name__ == '__main__':
    setup_models_directory()
    if not check_models_exist():
        create_dummy_models()
